export type ModelProvider =
  | "openai"
  | "google"
  | "anthropic"
  | "mistral"
  | "groq"
  | "perplexity"
  | "ollama"
  | "openrouter"
  | "together"
  | "gooseai"
  | "cohere"
  | "cloudflare"
  | "custom"
